apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: openstack-small-pool-enterprise
  namespace: garm-operator-system
spec:
  githubScopeRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: Enterprise
    name: enterprise-sample
  enabled: true
  extraSpecs: "{}"
  flavor: small
  githubRunnerGroup: ""
  imageName: runner-default
  maxRunners: 4
  minIdleRunners: 2
  osArch: amd64
  osType: linux
  providerName: openstack # this is the name defined in your garm server
  runnerBootstrapTimeout: 20
  runnerPrefix: ""
  tags:
    - linux
    - small
    - ubuntu
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: openstack-medium-pool-org
  namespace: garm-operator-system
spec:
  githubScopeRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: Organization
    name: github-actions
  enabled: true
  extraSpecs: "{}"
  flavor: medium
  githubRunnerGroup: ""
  imageName: runner-default
  maxRunners: 4
  minIdleRunners: 2
  osArch: amd64
  osType: linux
  providerName: openstack # this is the name defined in your garm server
  runnerBootstrapTimeout: 20
  runnerPrefix: ""
  tags:
    - linux
    - medium
    - ubuntu
---
apiVersion: garm-operator.mercedes-benz.com/v1alpha1
kind: Pool
metadata:
  labels:
    app.kubernetes.io/created-by: garm-operator
    app.kubernetes.io/instance: pool-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pool
    app.kubernetes.io/part-of: garm-operator
  name: openstack-medium-pool-repo
  namespace: garm-operator-system
spec:
  githubScopeRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: Repository
    name: garm-operator
  enabled: true
  extraSpecs: "{}"
  flavor: medium
  githubRunnerGroup: ""
  imageName: runner-default
  maxRunners: 4
  minIdleRunners: 2
  osArch: amd64
  osType: linux
  providerName: openstack
  runnerBootstrapTimeout: 20
  runnerPrefix: ""
  tags:
    - linux
    - medium
    - ubuntu
